language: elixir
elixir:
  - 1.3.0
otp_release:
  - 19.0
  - 18.0
sudo: false
notifications:
  recipients:
    - milmazz@gmail.com
env:
  - MIX_ENV=test
script:
  - "mix do local.hex --force, deps.get, test"
cache:
  directories:
    - deps
